flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- Crypto-4.2.5.1
- HTTP-4000.2.20
- HUnit-1.3.0.0
- MissingH-1.3.0.1
- QuickCheck-2.8.1
- aeson-0.10.0.0
- aeson-pretty-0.7.2
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- appar-0.1.4
- async-2.0.2
- attoparsec-0.13.0.1
- auto-update-0.1.2.2
- base64-bytestring-1.0.0.1
- blaze-builder-0.4.0.1
- blaze-html-0.8.1.0
- blaze-markup-0.7.0.2
- byteable-0.1.1
- byteorder-1.0.4
- bytestring-builder-0.10.6.0.0
- case-insensitive-1.2.0.4
- cmdargs-0.10.13
- conduit-1.2.5
- conduit-extra-1.1.9.1
- configurator-0.3.0.0
- cookie-0.4.1.6
- cpphs-1.19.3
- cryptohash-0.11.6
- cryptohash-conduit-0.1.1
- data-default-class-0.0.1
- dataenc-0.12
- dlist-0.7.1.2
- easy-file-0.2.1
- exceptions-0.8.0.2
- fast-logger-2.4.1
- file-embed-0.0.9
- hS3-0.5.9
- hashable-1.2.3.3
- haskell-src-exts-1.16.0.1
- haskell-src-meta-0.6.0.10
- hex-0.1.2
- hslogger-1.2.9
- hspec-2.2.0
- hspec-core-2.2.0
- hspec-discover-2.2.0
- hspec-expectations-0.7.2
- http-date-0.0.6.1
- http-types-0.8.6
- http2-1.0.4
- hxt-9.3.1.15
- hxt-charproperties-9.2.0.1
- hxt-regex-xmlschema-9.2.0.2
- hxt-unicode-9.0.2.4
- interpolate-0.1.0
- iproute-1.7.0
- lifted-base-0.2.3.6
- mime-mail-0.4.10
- mime-types-0.1.0.6
- mmorph-1.0.4
- monad-control-1.0.0.4
- mtl-2.2.1
- mwc-random-0.13.3.2
- nats-1
- network-2.6.2.1
- network-uri-2.6.0.3
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.11.0.2
- parsec-3.1.9
- polyparse-1.11
- postgresql-libpq-0.9.1.1
- postgresql-simple-0.5.0.1
- primitive-0.6.1.0
- quickcheck-io-0.1.2
- random-1.1
- regex-base-0.93.2
- regex-compat-0.95.1
- regex-posix-0.95.2
- resourcet-1.1.6
- safe-0.3.9
- scientific-0.3.3.8
- semigroups-0.17.0.1
- setenv-0.1.1.3
- simple-sendfile-0.2.21
- split-0.2.2
- stm-2.4.4
- streaming-commons-0.1.14
- string-conversions-0.4
- stringsearch-0.3.6.6
- syb-0.5.1
- system-filepath-0.4.13.4
- tagged-0.8.1
- text-1.2.1.3
- tf-random-0.5
- th-expand-syns-0.3.0.6
- th-lift-0.7.2
- th-orphans-0.12.2
- th-reify-many-0.1.3
- transformers-base-0.4.4
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unix-time-0.3.5
- unordered-containers-0.2.5.1
- utf8-string-1.0.1.1
- uuid-types-1.0.2
- vault-0.3.0.4
- vector-0.11.0.0
- void-0.7.1
- wai-3.0.3.0
- wai-app-static-3.1.1
- wai-extra-3.0.10
- wai-logger-2.2.4.1
- warp-3.1.3
- word8-0.1.2
- zlib-0.6.1.1
resolver: ghc-7.10.1
